/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import { View, Text } from 'react-native';
import Drag from 'react-native-drag';

function App() {
  return (
    <View>
      <Text>
        <Drag />
      </Text>
    </View>
  );
}

export default App;
